"""Suggested opening lines for the sender page.

Structured data, not markup: category -> list of openers, per language. The
page always shows exactly three, drawn from three *different* categories so a
visitor sees a range of tone (warm / curious / memory ...) rather than three
variations of the same thing. Every line is an open-ended, kind way to start a
message — nothing that pressures, flatters manipulatively or fishes for a
reaction.
"""

import random

PROMPT_COUNT = 3

POOL: dict[str, dict[str, list[str]]] = {
    "uz": {
        "warm": [
            "Sen haqingda...",
            "Senga rahmat aytmoqchiman...",
            "Sen borligingdan xursandman...",
            "Sen menga ilhom berasan...",
            "Sen shunday odamsanki...",
            "Sening kulgingni...",
            "Senga omad tilayman...",
            "Sen meni qo'llab-quvvatlading...",
            "Sendan minnatdorman...",
            "Sening mehribonligingni...",
            "Har doim senga aytmoqchi edim...",
            "Sen juda yaxshi do'stsan...",
            "Bugun senga aytmoqchiman...",
            "Sen bilan faxrlanaman...",
            "Sen kuchli odamsan...",
            "Sen tufayli...",
            "Senga yaxshi kunlar tilayman...",
            "Sening yordaming...",
            "Senda menga yoqadigan narsa...",
            "Sen bilan gaplashish...",
            "Sening ishonchingga...",
            "Sen atrofingdagilarga...",
            "Sening samimiyliging...",
            "Sen haqingdagi eng yaxshi narsa...",
            "Sen bilan o'zimni yaxshi his qilaman...",
        ],
        "curious": [
            "Bir savolim bor...",
            "Hozir nimani o'rganayapsan?",
            "Sevimli kitobing qaysi?",
            "Eng sevimli qo'shig'ing nima?",
            "Qaysi kasbni orzu qilgansan?",
            "Eng ko'p qayerga bormoqchisan?",
            "Hozir nima haqida o'ylayapsan?",
            "Qanday musiqa tinglaysan?",
            "Seni nima kuldiradi?",
            "Eng yaxshi olgan maslahating...",
            "Kelajakda nima qilmoqchisan?",
            "Bo'sh vaqtingda nima qilasan?",
            "Sevimli ovqating qaysi?",
            "Qaysi filmni qayta-qayta ko'rasan?",
            "Sen haqingda bilmoqchi edim...",
            "Yashirin qobiliyating bormi?",
            "Qaysi davlatga borishni istaysan?",
            "Eng katta orzuing nima?",
            "Kunni nima bilan boshlaysan?",
            "Seni nima ilhomlantiradi?",
            "Yaqinda nimani yangi bilib oldin?",
            "Sevimli faslingiz qaysi?",
            "Bir narsani so'ramoqchiman...",
            "Senga qiziq bo'lgan narsa...",
            "Bugun kayfiyating qanday?",
        ],
        "social": [
            "Sen bilan tanishganimizda...",
            "Guruhimizda sen...",
            "Sen bilan o'qigan kunlar...",
            "Sen bilan bir jamoada...",
            "Sening do'stlaring...",
            "Bir kun birga...",
            "Sen bilan suhbat...",
            "Sen bizning...",
            "Sen bilan ishlash...",
            "Sen bilan choy ichgim keladi...",
            "Kimdir senga aytishi kerak edi...",
            "Sen bilan sayr qilish...",
            "Sen bilan gaplashgim keladi...",
            "Yana qachon uchrashamiz?",
            "Odamlarni birlashtirasan...",
            "Do'stlar orasida sen...",
            "Sening energiyang...",
            "Sen kirsang, davra...",
            "Sen bilan bir xonada...",
            "Sen bilan hamkorlik...",
            "Sen bilan birga bo'lganda...",
            "Sen tanishtirgan odamlar...",
            "Sening davrangda...",
            "Sen yig'ilishlarda...",
            "Sen bilan bir kun...",
        ],
        "memory": [
            "Eng yaxshi xotiram sen bilan...",
            "Seni birinchi marta ko'rganimda...",
            "Esingdami, bir kuni...",
            "Seni eslasam...",
            "Sen bilan o'tgan yoz...",
            "Sen bilan bo'lgan eng kulgili voqea...",
            "Bir kuni sen menga...",
            "Sen aytgan gap hali ham esimda...",
            "Birinchi suhbatimiz...",
            "Sen bilan qilgan sayohat...",
            "Sen bilan o'tgan kechalar...",
            "O'sha kuni sen...",
            "Birga o'tgan kunlarni sog'inaman...",
            "Bolaligimizda...",
            "Sen bilan birinchi uchrashuvimiz...",
            "Sen menga yordam bergan kun...",
            "O'qigan yillarimiz...",
            "Bir qo'shiq seni eslatadi...",
            "Sen bilan o'tgan bayram...",
            "Eng esda qolgan gaping...",
            "Sen bilan birga kulgan payt...",
            "Sen bilan o'sha suhbat...",
            "Seni eslatadigan narsa...",
            "Sen bilan tanishganimdan beri...",
            "Aytolmagan bir gapim bor...",
        ],
        "fun": [
            "Agar sen kino qahramoni bo'lsang...",
            "Seni bir so'z bilan aytsam...",
            "Sening superkuching...",
            "Sen bilan sarguzasht...",
            "Agar sen hayvon bo'lsang...",
            "Seni eng ko'p kuldirgan narsa...",
            "Sening mashhur gaping...",
            "Bir sirni aytaymi...",
            "Sen haqingda kulgili fikr...",
            "Agar sen qo'shiq bo'lsang...",
            "Sening kulgili odating...",
            "Sen bilan pitsa yesak...",
            "Agar sen ob-havo bo'lsang...",
            "Sen haqingda bir haqiqat...",
            "Bugungi kayfiyatim...",
            "Ismingni eshitsam...",
            "Sen bilan o'yin o'ynasak...",
            "Sening eng yaxshi latifang...",
            "Agar sen bir rang bo'lsang...",
            "Sen bilan kofe ichsak...",
            "Senga bir qo'shiq bag'ishlasam...",
            "Sening kulgining yuqumli...",
            "Sen doim...",
            "Agar sen kitob bo'lsang...",
            "Sen bilan bir kun almashsak...",
        ],
        "deep": [
            "Sen menga o'rgatding...",
            "Sen tufayli men...",
            "Ba'zan o'ylayman...",
            "Senga bir narsani tan olmoqchiman...",
            "Sen hayotimga...",
            "Sen bilan gaplashgach...",
            "Sendan o'rganganim...",
            "Bir narsani o'zgartira olsam...",
            "Seni tushunaman...",
            "Uzr so'ramoqchiman...",
            "Qiyin paytda sen...",
            "Sen hech qachon bilmagan...",
            "Meni o'zgartirgan narsa...",
            "Senga ishonaman, chunki...",
            "O'zingga ishon...",
            "Hayotda muhim narsa...",
            "Seni ko'rib men...",
            "Sening yo'ling...",
            "Senga eslatmoqchiman...",
            "Sen o'ylagandan ko'proq...",
            "Sen yolg'iz emassan...",
            "Umid qilamanki, sen...",
            "Sen haqingda o'ylaganimda...",
            "Sening kuching...",
            "Hech kim aytmagan bo'lsa...",
        ],
    },
    "ru": {
        "warm": [
            "О тебе...",
            "Хочу сказать тебе спасибо...",
            "Я рад, что ты есть...",
            "Ты меня вдохновляешь...",
            "Ты такой человек, что...",
            "Твоя улыбка...",
            "Желаю тебе...",
            "Ты меня поддержал(а)...",
            "Я благодарен тебе за...",
            "Твоя доброта...",
            "Давно хотел тебе сказать...",
            "Ты очень хороший друг...",
            "Сегодня хочу сказать тебе...",
            "Я горжусь тобой...",
            "Ты сильный человек...",
            "Благодаря тебе...",
            "Желаю тебе добрых дней...",
            "Твоя помощь...",
            "Мне в тебе нравится...",
            "Разговаривать с тобой...",
            "Твоё доверие...",
            "Ты для окружающих...",
            "Твоя искренность...",
            "Лучшее, что есть в тебе...",
            "С тобой мне спокойно...",
        ],
        "curious": [
            "У меня есть вопрос...",
            "Чему ты сейчас учишься?",
            "Какая у тебя любимая книга?",
            "Какая твоя любимая песня?",
            "О какой профессии ты мечтал(а)?",
            "Куда бы ты хотел(а) поехать?",
            "О чём ты сейчас думаешь?",
            "Какую музыку ты слушаешь?",
            "Что тебя смешит?",
            "Лучший совет, что ты получал(а)...",
            "Кем ты хочешь стать?",
            "Чем ты занимаешься в свободное время?",
            "Какое твоё любимое блюдо?",
            "Какой фильм ты пересматриваешь?",
            "Хотел узнать о тебе...",
            "У тебя есть скрытый талант?",
            "В какую страну ты хочешь поехать?",
            "О чём ты мечтаешь больше всего?",
            "С чего ты начинаешь день?",
            "Что тебя вдохновляет?",
            "Что нового ты узнал(а) недавно?",
            "Какое твоё любимое время года?",
            "Хочу кое о чём спросить...",
            "Что тебе интересно?",
            "Какое у тебя сегодня настроение?",
        ],
        "social": [
            "Когда мы познакомились...",
            "В нашей компании ты...",
            "Наши дни учёбы...",
            "В одной команде с тобой...",
            "Твои друзья...",
            "Однажды вместе...",
            "Разговор с тобой...",
            "Ты у нас...",
            "Работать с тобой...",
            "Хочу выпить с тобой чаю...",
            "Кто-то должен был тебе сказать...",
            "Гулять с тобой...",
            "Хочу с тобой поговорить...",
            "Когда мы снова встретимся?",
            "Ты объединяешь людей...",
            "Среди друзей ты...",
            "Твоя энергия...",
            "Когда ты заходишь, вокруг...",
            "В одной комнате с тобой...",
            "Сотрудничать с тобой...",
            "Когда мы вместе...",
            "Люди, которых ты познакомил(а)...",
            "В твоей компании...",
            "На встречах ты...",
            "Один день с тобой...",
        ],
        "memory": [
            "Лучшее воспоминание с тобой...",
            "Когда я увидел тебя впервые...",
            "Помнишь, однажды...",
            "Когда я вспоминаю тебя...",
            "Лето с тобой...",
            "Самый смешной случай с тобой...",
            "Однажды ты мне...",
            "Твои слова я помню до сих пор...",
            "Наш первый разговор...",
            "Наша поездка...",
            "Наши вечера...",
            "В тот день ты...",
            "Скучаю по нашим дням...",
            "В детстве мы...",
            "Наша первая встреча...",
            "День, когда ты мне помог(ла)...",
            "Наши годы учёбы...",
            "Одна песня напоминает мне о тебе...",
            "Праздник с тобой...",
            "Твоя самая запоминающаяся фраза...",
            "Когда мы вместе смеялись...",
            "Тот разговор с тобой...",
            "Вещь, которая напоминает о тебе...",
            "С тех пор как мы познакомились...",
            "Есть кое-что, что я не решался сказать...",
        ],
        "fun": [
            "Если бы ты был(а) героем фильма...",
            "Если описать тебя одним словом...",
            "Твоя суперсила...",
            "Приключение с тобой...",
            "Если бы ты был(а) животным...",
            "Что тебя смешит больше всего?",
            "Твоя коронная фраза...",
            "Расскажу секрет...",
            "Забавная мысль о тебе...",
            "Если бы ты был(а) песней...",
            "Твоя смешная привычка...",
            "Пицца с тобой...",
            "Если бы ты был(а) погодой...",
            "Один факт о тебе...",
            "Моё настроение сегодня...",
            "Когда я слышу твоё имя...",
            "Поиграем вместе...",
            "Твоя лучшая шутка...",
            "Если бы ты был(а) цветом...",
            "Кофе с тобой...",
            "Если бы я посвятил(а) тебе песню...",
            "Твой смех заразителен...",
            "Ты всегда...",
            "Если бы ты был(а) книгой...",
            "Если бы мы поменялись днями...",
        ],
        "deep": [
            "Ты меня научил(а)...",
            "Из-за тебя я...",
            "Иногда я думаю...",
            "Хочу тебе в чём-то признаться...",
            "Ты в моей жизни...",
            "После разговора с тобой...",
            "От тебя я узнал(а)...",
            "Если бы я мог(ла) что-то изменить...",
            "Я тебя понимаю...",
            "Хочу извиниться...",
            "В трудную минуту ты...",
            "Ты никогда не узнаешь...",
            "Меня изменило то, что...",
            "Я тебе доверяю, потому что...",
            "Верь в себя...",
            "В жизни важно...",
            "Глядя на тебя, я...",
            "Твой путь...",
            "Хочу тебе напомнить...",
            "Ты больше, чем думаешь...",
            "Ты не один(одна)...",
            "Надеюсь, ты...",
            "Когда я думаю о тебе...",
            "Твоя сила...",
            "Если тебе никто не говорил...",
        ],
    },
}


def _pool(lang: str) -> dict[str, list[str]]:
    return POOL.get(lang, POOL["uz"])


def pick_prompts(lang: str, k: int = PROMPT_COUNT, rng: random.Random | None = None) -> list[dict]:
    """k prompts, each from a different category (falls back gracefully if a
    pool ever has fewer than k categories)."""
    rng = rng or random
    pool = _pool(lang)
    categories = rng.sample(list(pool), k=min(k, len(pool)))
    picked = []
    for cat in categories:
        idx = rng.randrange(len(pool[cat]))
        picked.append({"id": f"{cat}-{idx}", "category": cat, "text": pool[cat][idx]})
    return picked


def pool_payload(lang: str) -> list[list]:
    """Compact [id, category, text] rows for the client, which uses them only
    to avoid repeating the previous visit's three on a return visit."""
    return [[f"{cat}-{i}", cat, text] for cat, items in _pool(lang).items() for i, text in enumerate(items)]
